services:
  - type: web
    name: greeting-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.app:app
    envVars:
      - key: GOOGLE_TRANSLATE_API_KEY
        sync: false 